#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/tucana

PRODUCT_COPY_FILES += \
    vendor/xiaomi/tucana/proprietary/vendor/etc/acdbdata/Tutu/Tutu_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Tutu/Tutu_Bluetooth_cal.acdb \
    vendor/xiaomi/tucana/proprietary/vendor/etc/acdbdata/Tutu/Tutu_Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Tutu/Tutu_Codec_cal.acdb \
    vendor/xiaomi/tucana/proprietary/vendor/etc/acdbdata/Tutu/Tutu_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Tutu/Tutu_General_cal.acdb \
    vendor/xiaomi/tucana/proprietary/vendor/etc/acdbdata/Tutu/Tutu_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Tutu/Tutu_Global_cal.acdb \
    vendor/xiaomi/tucana/proprietary/vendor/etc/acdbdata/Tutu/Tutu_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Tutu/Tutu_Handset_cal.acdb \
    vendor/xiaomi/tucana/proprietary/vendor/etc/acdbdata/Tutu/Tutu_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Tutu/Tutu_Hdmi_cal.acdb \
    vendor/xiaomi/tucana/proprietary/vendor/etc/acdbdata/Tutu/Tutu_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Tutu/Tutu_Headset_cal.acdb \
    vendor/xiaomi/tucana/proprietary/vendor/etc/acdbdata/Tutu/Tutu_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Tutu/Tutu_Speaker_cal.acdb \
    vendor/xiaomi/tucana/proprietary/vendor/etc/acdbdata/Tutu/Tutu_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Tutu/Tutu_workspaceFile.qwsp \
    vendor/xiaomi/tucana/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/CFR_para_T_2x_V03.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_T_2x_V03.bin \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/CFR_para_T_4x_V03.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_T_4x_V03.bin \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/CFR_para_UW_V01.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_UW_V01.bin \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/CFR_para_W_V08.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_W_V08.bin \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/GpuKernelRepo.pb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/GpuKernelRepo.pb \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/LDC_FPC_TUNING_DATA.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_FPC_TUNING_DATA.bin \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/LDC_PACKDATA_VENDORID_0x01.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_PACKDATA_VENDORID_0x01.bin \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/LDC_PACKDATA_VENDORID_0x07.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_PACKDATA_VENDORID_0x07.bin \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/LDC_table_src1.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_table_src1.dat \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/LDC_table_src2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_table_src2.dat \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/almalence_sr_params_tele.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_tele.config \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/almalence_sr_params_tele4x.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_tele4x.config \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/almalence_sr_params_tele4x_moon.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_tele4x_moon.config \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/almalence_sr_params_tele4x_zoom20x.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_tele4x_zoom20x.config \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/almalence_sr_params_tele4x_zoom30x.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_tele4x_zoom30x.config \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/almalence_sr_params_tele4x_zoom40x.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_tele4x_zoom40x.config \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/almalence_sr_params_wide-108M-remosaic.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_wide-108M-remosaic.config \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/almalence_sr_params_wide-27M-binning.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_wide-27M-binning.config \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/almalence_sr_params_wide.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_wide.config \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/beauty_ui9_intelligent_params.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/beauty_ui9_intelligent_params.config \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/body_slim_ui9_params.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/body_slim_ui9_params.config \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/eisoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/eisoverridesettings.txt \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/golden_rear_dc_cal_tt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/golden_rear_dc_cal_tt.bin \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/golden_rear_dc_cal_wt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/golden_rear_dc_cal_wt.bin \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/golden_rear_dc_cal_wu.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/golden_rear_dc_cal_wu.bin \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/hdr_ui9_params.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hdr_ui9_params.config \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/hdrd_ui9_params.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hdrd_ui9_params.config \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/mibokeh_712_opencl.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mibokeh_712_opencl.bin \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/mibokeh_712_parameter.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mibokeh_712_parameter.bin \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/model.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model.dat \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/model_back.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_back.dlc \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/model_front.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_front.dlc \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/morpho_lowlight4.0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight4.0.xml \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/morpho_lowlight4.0_3hdr.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight4.0_3hdr.xml \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/morpho_lowlight4.0_adrc_high.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight4.0_adrc_high.xml \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/morpho_lowlight4.0_adrc_high_1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight4.0_adrc_high_1.xml \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/multianchor.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/multianchor.txt \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sceneDetection.xml \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/style/model.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/style/model.dat \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/visidon_clearshot_params_algoup.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/visidon_clearshot_params_algoup.xml \
    vendor/xiaomi/tucana/proprietary/vendor/etc/camera/watermark_font_2300_3199.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/watermark_font_2300_3199.dat \
    vendor/xiaomi/tucana/proprietary/vendor/etc/elliptic_sensor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/elliptic_sensor.xml \
    vendor/xiaomi/tucana/proprietary/vendor/etc/init/init.batterysecret.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.batterysecret.rc \
    vendor/xiaomi/tucana/proprietary/vendor/etc/init/init.mi_thermald.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.mi_thermald.rc \
    vendor/xiaomi/tucana/proprietary/vendor/etc/init/init.vendor.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sensors.rc \
    vendor/xiaomi/tucana/proprietary/vendor/etc/init/vendor.sensors.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.qti.rc \
    vendor/xiaomi/tucana/proprietary/vendor/etc/screen_light.xml:$(TARGET_COPY_OUT_VENDOR)/etc/screen_light.xml \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/adux1050_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/adux1050_0.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_dri_0.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dso_0.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sm6150_adux1050_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm6150_adux1050_0.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sm6150_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm6150_ak991x_0.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sm6150_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm6150_lsm6dso_0.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sm6150_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm6150_power_0.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sm6150_tcs3701.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm6150_tcs3701.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sm6150_vl53l1_tof_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm6150_vl53l1_tof_0.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_aod.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aod.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_nonui.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_nonui.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/tcs3701.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tcs3701.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/config/vl53l1_tof_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/vl53l1_tof_0.json \
    vendor/xiaomi/tucana/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/xiaomi/tucana/proprietary/vendor/etc/thermal-arvr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-arvr.conf \
    vendor/xiaomi/tucana/proprietary/vendor/etc/thermal-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-camera.conf \
    vendor/xiaomi/tucana/proprietary/vendor/etc/thermal-chg-only.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-chg-only.conf \
    vendor/xiaomi/tucana/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/xiaomi/tucana/proprietary/vendor/etc/thermal-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map.conf \
    vendor/xiaomi/tucana/proprietary/vendor/etc/thermal-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-nolimits.conf \
    vendor/xiaomi/tucana/proprietary/vendor/etc/thermal-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-normal.conf \
    vendor/xiaomi/tucana/proprietary/vendor/etc/thermal-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-phone.conf \
    vendor/xiaomi/tucana/proprietary/vendor/etc/thermal-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-tgame.conf \
    vendor/xiaomi/tucana/proprietary/vendor/etc/thermald-devices.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermald-devices.conf \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/a615_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a615_zap.b00 \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/a615_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a615_zap.b01 \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/a615_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a615_zap.b02 \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/a615_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a615_zap.elf \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/a615_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a615_zap.mdt \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/a618_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a618_gmu.bin \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/a630_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_sqe.fw \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/drv2604.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/drv2604.bin \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.elf \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/tucana_ois.coeff:$(TARGET_COPY_OUT_VENDOR)/firmware/tucana_ois.coeff \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/tucana_ois.prog:$(TARGET_COPY_OUT_VENDOR)/firmware/tucana_ois.prog \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/tucana_tele4x_ois.coeff:$(TARGET_COPY_OUT_VENDOR)/firmware/tucana_tele4x_ois.coeff \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/tucana_tele4x_ois.mem:$(TARGET_COPY_OUT_VENDOR)/firmware/tucana_tele4x_ois.mem \
    vendor/xiaomi/tucana/proprietary/vendor/firmware/tucana_tele4x_ois.prog:$(TARGET_COPY_OUT_VENDOR)/firmware/tucana_tele4x_ois.prog \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.sensormodule.tucana_semco_imx350.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.tucana_semco_imx350.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.sensormodule.tucana_semco_ov08a10.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.tucana_semco_ov08a10.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.sensormodule.tucana_semco_s5k2l7.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.tucana_semco_s5k2l7.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.sensormodule.tucana_semco_s5k2l7_v1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.tucana_semco_s5k2l7_v1.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.sensormodule.tucana_semco_s5khmx.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.tucana_semco_s5khmx.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.sensormodule.tucana_semco_s5khmx_8plens.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.tucana_semco_s5khmx_8plens.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.sensormodule.tucana_sunny_ov02a10.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.tucana_sunny_ov02a10.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.sensormodule.tucana_sunny_s5kgd1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.tucana_sunny_s5kgd1.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.tucana_semco_imx350.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tucana_semco_imx350.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.tucana_semco_imx350_global.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tucana_semco_imx350_global.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.tucana_semco_ov08a10.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tucana_semco_ov08a10.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.tucana_semco_ov08a10_global.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tucana_semco_ov08a10_global.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.tucana_semco_s5k2l7.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tucana_semco_s5k2l7.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.tucana_semco_s5k2l7_global.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tucana_semco_s5k2l7_global.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.tucana_semco_s5khmx.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tucana_semco_s5khmx.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.tucana_semco_s5khmx_8plens.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tucana_semco_s5khmx_8plens.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.tucana_semco_s5khmx_8plens_global.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tucana_semco_s5khmx_8plens_global.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.tucana_semco_s5khmx_global.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tucana_semco_s5khmx_global.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.tucana_sunny_ov02a10.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tucana_sunny_ov02a10.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.tucana_sunny_ov02a10_global.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tucana_sunny_ov02a10_global.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.tucana_sunny_s5kgd1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tucana_sunny_s5kgd1.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/com.qti.tuned.tucana_sunny_s5kgd1_global.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tucana_sunny_s5kgd1_global.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/components/etc/visidon_clearshot_params.xml:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/components/etc/visidon_clearshot_params.xml \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/xiaomi/tucana/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin

PRODUCT_PACKAGES += \
    btaudio_offload_if \
    audio.primary.sm6150 \
    liba2dpoffload \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadm \
    libaudcal \
    libaudio_log_utils \
    libaudioparsers \
    libaudioroute_ext \
    libhdmiedid \
    libhfp \
    libqtigef \
    libsndmonitor \
    libspkrprot \
    libxlog \
    com.qti.sensor.imx350_tucana \
    com.qti.sensor.ov02a10_tucana \
    com.qti.sensor.ov08a10_tucana \
    com.qti.sensor.s5k2l7 \
    com.qti.sensor.s5kgd1_tucana \
    com.qti.sensor.s5khmx_tucana \
    com.almalence.node.sr \
    com.altek.node.depurple \
    com.altek.node.distortioncorrection \
    com.arcsoft.node.bodyslim \
    com.arcsoft.node.capturebokeh \
    com.arcsoft.node.deflicker \
    com.arcsoft.node.distortioncorrection \
    com.arcsoft.node.hdr \
    com.arcsoft.node.multicam_snapshot_fusion \
    com.arcsoft.node.realtimebokeh \
    com.arcsoft.node.skinbeautifier \
    com.arcsoft.node.smoothtransition \
    com.arcsoft.node.superlowlight \
    com.arcsoft.node.superlowlightraw \
    com.arcsoft.node.superportrait \
    com.mi.node.aiasd \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.depth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.mimovie \
    com.qti.node.photosolid \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swregistration \
    com.qti.node.watermark \
    com.qti.node.xiaomigenderage \
    com.qti.stats.aec \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.vidhance.node.eis \
    com.vidhance.stats.aec_dmbr \
    com.visidon.node.clearshot \
    com.visidon.node.sr \
    com.xiaomi.node.mibokeh \
    com.xiaomi.node.mifragment \
    com.xiaomi.node.misegment \
    libdepthmapwrapper \
    libmmcamera_cac3 \
    camera.qcom \
    com.qti.chi.override \
    fingerprint.fpc_fod.sm6150 \
    fingerprint.goodix_fod.sm6150 \
    libFaceGrade \
    libHalSuperSensorServer \
    libHalSuperSensorServerCWrapper \
    libSNPE \
    libSuperSensor \
    libSuperSensorCPU \
    libVDClearShot \
    libVDSuperPhotoAPI \
    libXMFD_AgeGender \
    lib_denoiser3 \
    libalAILDC \
    libalCFR \
    libalLDC \
    libalhLDC \
    libarcmulticamsat \
    libarcsoft_beautyshot \
    libarcsoft_bodyslim \
    libarcsoft_distortion_correction \
    libarcsoft_dualcam_optical_zoom_control \
    libarcsoft_dualcam_refocus \
    libarcsoft_dualcam_refocus_front \
    libarcsoft_dualcam_refocus_rear_t \
    libarcsoft_dualcam_refocus_rear_w \
    libarcsoft_hdr_detection \
    libarcsoft_hdrplus_hvx_stub \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_portrait_lighting \
    libarcsoft_portrait_lighting_c \
    libarcsoft_preview_deflicker \
    libarcsoft_super_night_raw \
    libarcsoft_supernight \
    libarcsoft_superportrait \
    libbase64 \
    libc++_shared \
    libcamera_dirty \
    libcamera_nn_stub \
    libcamera_scene \
    libcamxfdalgov7 \
    libcamxfdalgov8 \
    libcamxfdengine \
    libcamxstatscore \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libcapiv2svacnn \
    libcapiv2vop \
    libcom.qti.chinodeutils \
    libdng_sdkvendor \
    libflaw \
    libft2vendor \
    libgf_hal \
    libhta_hexagon_runtime \
    libmialgo_basic \
    libmialgo_fs \
    libmialgo_rfs \
    libmialgo_sd \
    libmialgo_utils \
    libmialgoengine \
    libmibokeh_712 \
    libmpbase \
    libmulticam_image_optical_zoom \
    libmulticam_optical_zoom_control \
    libmulticam_video_optical_zoom \
    libnanopb \
    libnotifyaudiohal \
    libremosaic_wrapper \
    libremosaichvx_stub \
    libremosaiclib \
    libsensorslog \
    libsn100u_fw \
    libsnpe_dsp_domains_v2 \
    libsns_device_mode_stub \
    libsns_fastRPC_util \
    libsns_low_lat_stream_stub \
    libsns_registry_skel \
    libsnsapi \
    libsnsdiaglog \
    libssc \
    libswregistrationalgo \
    libswvdec \
    libsymphony-cpu \
    libsysmon_cdsp_skel \
    libthermalclient \
    libtriplecam_optical_zoom_control \
    libultrasound \
    libvidhance \
    sensors.elliptic \
    sensors.mius.proximity \
    sensors.ssc \
    sensors.touch \
    vendor.qti.hardware.camera.device@3.5 \
    capi_v2_aptX_CLHDAD_Encoder \
    capi_v2_aptX_Classic \
    capi_v2_aptX_HD \
    dirac_resource \
    libSuperSensor_skel \
    libVC1Dec \
    libVC1DecDsp_skel \
    libVDHexagonSuperPhoto_skel \
    libapps_mem_heap \
    libarcsoft_dualcam_refocus_skel \
    libarcsoft_hdrplus_hvx_skel \
    libcamera_nn_skel \
    libcvpdsp_skel \
    libdirac-capiv2 \
    libdspCV_skel \
    libdsp_streamer_add_constant \
    libdsp_streamer_binning \
    libdsp_streamer_skel \
    libfastcvadsp \
    libfastcvdsp_skel \
    libhexagon_nn_skel \
    libhexagon_nn_skel_secondary \
    libremosaichvx_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    libsnpe_dsp_v65_domains_v2_skel \
    libsnpe_dsp_v66_domains_v2_skel \
    libsns_device_mode_skel \
    libsns_low_lat_stream_skel \
    misound_karaoke_res \
    misound_karaokemix_res \
    misound_res \
    batterysecret \
    mi_thermald \
    sensors.qti \
    thermal-engine
